{{- $global := . -}}
{{- $common := $global.Values.common | default dict -}}
{{- if and ($global.Values.enabled) ($global.Values.cribNetworkPolicy.enabled) }}
{{- $labels := dict "global" $global "merged" $global.Values.common "nodeName" "stub" | include "chainlink-cluster.labelMachine" | fromYaml }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "chainlink-cluster.fullname" . }}-netpol-crib
  namespace: {{ .Release.Namespace }}
  labels: {{ $labels.cluster | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{ $labels.clusterSelector | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
  {{- if not (empty .Values.cribNetworkPolicy.ingress.customCidrs) }}
    - from:
      {{- with .Values.cribNetworkPolicy.ingress.extraIngressSelectors -}}
          {{ toYaml . | nindent 6 }}
      {{- end }}
      {{- range $cidr := .Values.cribNetworkPolicy.ingress.customCidrs }}
      - ipBlock:
          cidr: {{ $cidr | quote }}
      {{- end }}
      ports:
        # http(s) access from internal network
        - port: {{ .Values.common.ports.ui | default (include "chainlink-cluster.uiPort" .) }}
          protocol: TCP
        # P2P access from internal network
        - port: {{ .Values.common.ports.p2pv1 | default 6690 }}
          protocol: TCP
        - port: {{ .Values.common.ports.p2pv2 | default 5001 }}
          protocol: TCP
  {{- else }}
    # Deny all ingress if no rules are specified. Rules can still be specified in other templates.
    - { }
  {{- end }}
  egress:
    # Allows to add extra egress rules
    {{- with .Values.cribNetworkPolicy.egress.extraEgressRules -}}
        {{ toYaml . | nindent 4 }}
    {{- end }}
    # Allow namespace local traffic
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: "{{ $.Release.Namespace }}"
    # Allow kube dns
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    # Allow node local dns
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: node-local-dns
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    # Allow egress to all hosts on port 443/tcp (HTTPS).
    - ports:
        - protocol: TCP
          port: 443
{{- end }}
