{{- $global := . -}}
{{- $common := $global.Values.common | default dict -}}
{{- if and ($global.Values.enabled) ($global.Values.common.vpn.enabled) }}
{{- $labels := dict "global" $global "merged" $global.Values.common "nodeName" "stub" | include "chainlink-cluster.labelMachine" | fromYaml }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "chainlink-cluster.fullname" . }}-netpol-egress-vpn
  namespace: {{ .Release.Namespace }}
  labels: {{ $labels.cluster | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{ $labels.clusterSelector | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    - to: # Allow database (RDS) access.
        - ipBlock:
            cidr: {{ .Values.common.vpn.rdsCidr }} # RDS endpoint private IP
      ports:
        - protocol: TCP
          port: 5432
    - to: # allow DNS resolution
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
        - ipBlock:
            cidr: {{ .Values.common.vpn.awsDNS  | default "0.0.0.0/0" }} # This rule allows to resolve DNS for the edge case the k8s DNS fails to resolve.
      ports: 
        - port: 53
          protocol: UDP
    # Allow node local dns
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: node-local-dns
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    # Allow access the Internet
    # required for blockchain RPC connectivity
    # limit to HTTPS
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
    # Allow access to the VPN CDIR.
    # Defined a wide port range to accomodate for different NOPs configurations.
    - to:
        - ipBlock:
            cidr: {{ .Values.common.vpn.vpnCidr }} 
      ports:
        - protocol: TCP
          port: 1025
          endPort: 65535
    # Allow access to the VPN endpoint - This is the Wireguard Gateway IP to which the node is going to connect to.
    - to:
        - ipBlock:
            cidr: {{ .Values.common.vpn.vpnEndpoint }} 
      ports: 
        - protocol: UDP
          port: {{ .Values.common.ports.vpn | default 51820 }}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "chainlink-cluster.fullname" . }}-netpol-ingress-vpn
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels: {{ $labels.clusterSelector | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    # p2p from VPN network 
    - from:
        - ipBlock:
            cidr:  {{ .Values.common.vpn.vpnCidr }}
      ports:
        - protocol: TCP
          port: {{ .Values.common.ports.p2pv2 | default 5001 }}
    # http(s) access from internal network
    - from:
        - ipBlock:
            cidr: 10.0.0.0/8
      ports: {{- include "chainlink-cluster.policyPrivatePorts" $global | indent 8 }}
{{- end }}
