repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: just
        args: ["fmt"]
        language: system
        types: [go]
        pass_filenames: false
        verbose: true

      - id: go-mod-tidy
        name: gomods tidy 
        entry: just 
        args: ["tidy"]
        language: system
        pass_filenames: false
        verbose: true