{{- $global := . -}}
{{- range until (include "chainlink-cluster.clusterSize" . | int) }}
  {{- $merged := dict "common" $global.Values.common "overrides" $global.Values.overrides "idx" . | include "chainlink-cluster.merged" | fromYaml -}}
  {{- if and ($global.Values.enabled) ($merged.chainlink.extraConfig) }}
  {{- $nodeName :=  dict "global" $global "merged" $merged "idx" . | include "chainlink-cluster.nodeName" -}}
  {{- $labels := dict "global" $global "merged" $merged "nodeName" $nodeName | include "chainlink-cluster.labelMachine" | fromYaml }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $nodeName }}-cm-extra
  labels: {{ $labels.instance | nindent 4 }}
data:
  {{- range $key, $value := $merged.chainlink.extraConfig }}
  {{ $key }}: {{- $value | toYaml | indent 1 }}
  {{- end }}
{{- end }}
{{- end }}
