{{- $global := . -}}
{{- range until (include "chainlink-cluster.clusterSize" . | int) }}
  {{- $merged := dict "common" $global.Values.common "overrides" $global.Values.overrides "idx" . | include "chainlink-cluster.merged" | fromYaml -}}
  {{- if and ($global.Values.enabled) ($merged.persistence.enabled) }}
  {{- $nodeName :=  dict "global" $global "merged" $merged "idx" . | include "chainlink-cluster.nodeName" -}}
  {{- $labels := dict "global" $global "merged" $merged "nodeName" $nodeName | include "chainlink-cluster.labelMachine" | fromYaml }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $nodeName }}-pvc
  labels: {{ $labels.instance | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: {{ $merged.persistence.size | default "1Gi" }}
  {{- end }}
{{- end }}
