{{- $global := . -}}
{{- range until (include "chainlink-cluster.clusterSize" . | int) }}
  {{- $merged := dict "common" $global.Values.common "overrides" $global.Values.overrides "idx" . | include "chainlink-cluster.merged" | fromYaml -}}
  {{- if and ($global.Values.enabled) ($global.Values.gatewayMode.enabled) }}
  {{- $nodeName :=  dict "global" $global "merged" $merged "idx" . | include "chainlink-cluster.nodeName" -}}
  {{- $labels := dict "global" $global "merged" $merged "nodeName" $nodeName | include "chainlink-cluster.labelMachine" | fromYaml }}
---
# Gateway Node service per each node
apiVersion: v1
kind: Service
metadata:
  name: {{ $nodeName }}-gtwnode
  labels: {{ $labels.instance | nindent 4 }}
spec:
  type: {{ $global.Values.gatewayMode.serviceType }}
  selector: {{ $labels.instanceSelector | nindent 4 }}
  ports:
    - port: {{ include "chainlink-cluster.gatewayNodePort" . }}
      targetPort: gateway-node
      name: gateway-node
      protocol: TCP
  {{- end }}
{{- end }}
