{{- if .Values.envSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace  }}
type: Opaque
stringData:
  {{ .Values.envSecrets | toYaml | nindent 2 }}
{{- end }}
