{{- if .Values.volumeSecrets }}
{{- range .Values.volumeSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace  }}
type: Opaque
stringData:
  {{ .filename }}: |
{{ .secret  | indent 4}}
{{- end }}
{{- end }}
