root = ".."

[build]
cmd = "go build -o ./tmp/tokenVerifier /app/cmd/tokenVerifier"
bin = "tmp/tokenVerifier"
include_dir = ["app"]
include_ext = ["go", "mod", "sum"]
exclude_dir = ["tmp", "vendor", "testdata", ".git"]
