common:
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/certificate-arn: REDACTED-CERT-ARN
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
      alb.ingress.kubernetes.io/ssl-redirect: '443'
    hosts:
      - host: 'APP_NAME-%s.DOMAIN'
        paths:
          - path: /*
            pathType: ImplementationSpecific
        useNodeName: false
