common:
  vpn:
    enabled: true
    image:
      repository: linuxserver/wireguard
      pullPolicy: IfNotPresent
      tag: 1.0.20210914

overrides:
  - vpn:
      config:
        wg0.conf: |
          [Interface]
          Address = 10.22.32.60/32
          PrivateKey = REDACTED-0
          PostUp = ping -c1 10.22.32.1
          [Peer]
          PublicKey = 8dW3a6xAq9Kg20EUZrvhDtXrabIWCTTBxh4FUPRpa1o=
          AllowedIPs = 10.22.32.0/24
          Endpoint = 54.148.105.56:51820
          PersistentKeepalive = 25
  - vpn:
      config:
        wg0.conf: |
          [Interface]
          Address = 10.22.32.60/32
          PrivateKey = REDACTED-1
          PostUp = ping -c1 10.22.32.1
          [Peer]
          PublicKey = 8dW3a6xAq9Kg20EUZrvhDtXrabIWCTTBxh4FUPRpa1o=
          AllowedIPs = 10.22.32.0/24
          Endpoint = 54.148.105.56:51820
          PersistentKeepalive = 25
  - vpn:
      config:
        wg0.conf: |
          [Interface]
          Address = 10.22.32.60/32
          PrivateKey = REDACTED-2
          PostUp = ping -c1 10.22.32.1
          [Peer]
          PublicKey = 8dW3a6xAq9Kg20EUZrvhDtXrabIWCTTBxh4FUPRpa1o=
          AllowedIPs = 10.22.32.0/24
          Endpoint = 54.148.105.56:51820
          PersistentKeepalive = 25
  - vpn:
      config:
        wg0.conf: |
          [Interface]
          Address = 10.22.32.60/32
          PrivateKey = REDACTED-3
          PostUp = ping -c1 10.22.32.1
          [Peer]
          PublicKey = 8dW3a6xAq9Kg20EUZrvhDtXrabIWCTTBxh4FUPRpa1o=
          AllowedIPs = 10.22.32.0/24
          Endpoint = 54.148.105.56:51820
          PersistentKeepalive = 25
  - vpn:
      config:
        wg0.conf: |
          [Interface]
          Address = 10.22.32.60/32
          PrivateKey = REDACTED-4
          PostUp = ping -c1 10.22.32.1
          [Peer]
          PublicKey = 8dW3a6xAq9Kg20EUZrvhDtXrabIWCTTBxh4FUPRpa1o=
          AllowedIPs = 10.22.32.0/24
          Endpoint = 54.148.105.56:51820
          PersistentKeepalive = 25
