common:
  image:
    repository: public.ecr.aws/chainlink/chainlink
    tag: 2.5.0

  chainlinkNode:
    metadata:
      annotations:
        chainlinknode.k8s.chain.link/create-v2: 'true'
        chainlinknode.k8s.chain.link/init-rds: 'true'
        chainlinknode.k8s.chain.link/init-rds-idx: '0'
        chainlinknode.k8s.chain.link/preserve-ssm: 'true'
