nodeCount: 0
bootNodeCount: 2

nameOverride: ''
fullnameOverride: clc-misc-m-b
appLabelOverride: ''

networkPolicy:
  enabled: false

rollout:
  enabled: false

common:
  requiredLabels:
    app.kubernetes.io/component: chainlink-example-node
    app.chain.link/team: infra
    app.chain.link/product: example
    app.chain.link/blockchain: ethereum
    app.chain.link/network: sepolia
    app.chain.link/network-type: testnet

  service:
    private:
      type: ClusterIP

  ingress:
    enabled: false
    ingressClassName: alb
    annotations:
      {}
      # kubernetes.io/tls-acme: "true"
    hosts:
      # must be string template with one %s for index
      - host: chainlink-node-%s.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chainlink-node-tls
    #    hosts:
    #      - chainlink-node.local

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1024Mi

  servicemonitor:
    enabled: true

  nodeSelector: {}
  tolerations: []
  affinity: {}

overrides: []
