interval = "5s"
loglevel = "info"

[Monitoring]
Enabled = false
InsecureConnection = true
CACertFile = ""
OtelExporterGRPCEndpoint = ""
OtelExporterHTTPEndpoint = "otel-collector:4318"
LogStreamingEnabled = true
MetricReaderInterval = 5
TraceSampleRatio = 1.0
TraceBatchTimeout = 10

[EVM]
ChainID = "1337"

[EVM.Transactions.TransactionManagerV2]
Enabled = true
BlockTime = "1s"

[[EVM.Nodes]]
Name = "primary"
WSURL = "ws://blockchain-src:8545"
HTTPURL = "http://blockchain-src:8545"
