interval = "5s"
loglevel = "info"

[Monitoring]
Enabled = false
InsecureConnection = true
CACertFile = ""
OtelExporterGRPCEndpoint = ""
OtelExporterHTTPEndpoint = "otel-collector:4318"
LogStreamingEnabled = true
MetricReaderInterval = 5
TraceSampleRatio = 1.0
TraceBatchTimeout = 10

[KMS]
profile= "blah"
ecdsa_key_id = "yourkmskey"

[EVM]
ChainID = "11155111"  # Sepolia testnet

[EVM.Transactions.TransactionManagerV2]
Enabled = true
BlockTime = "12s"

[[EVM.Nodes]]
Name = "primary"
WSURL = "wss://ethereum-sepolia-rpc.publicnode.com"
HTTPURL = "https://ethereum-sepolia-rpc.publicnode.com"

[SOL]
ChainID = "testnet"

[[SOL.Nodes]]
Name = "primary"
URL = "https://api.testnet.solana.com"

