interval = "5s"
loglevel = "info"

[KMS]
profile= "blah"
ecdsa_key_id = "yourkmskey"

[EVM]
ChainID = "11155111"  # Sepolia testnet

[EVM.Transactions.TransactionManagerV2]
Enabled = true
BlockTime = "12s"

[[EVM.Nodes]]
Name = "primary"
WSURL = "wss://ethereum-sepolia-rpc.publicnode.com"
HTTPURL = "https://ethereum-sepolia-rpc.publicnode.com"

[SOL]
ChainID = "testnet"

[[SOL.Nodes]]
Name = "primary"
URL = "https://api.testnet.solana.com"

