name: chainlink-ccv-aggregator-2
envFromSecretsKeyRef:
  - envName: AGGREGATOR_STORAGE_CONNECTION_URL
    secretName: tbd
    secretKey: tbd
  - envName: AGGREGATOR_API_KEYS_JSON
    secretName: tbd
    secretKey: tbd