# name: chainlink-ccv-indexer
# envSecrets: {}
readinessProbe: null
livenessProbe: null
image:
  repository: 323150190480.dkr.ecr.us-west-2.amazonaws.com/chainlink-ccv-indexer
  tag: 14e7ceff998ed99b87a0482de504277b3dabdc57-rc
envVars:
  APP_NAME: chainlink-ccv-indexer
  INDEXER_CONFIG_PATH: /config/indexer.toml
resources:
  limits:
    cpu: 1
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
labels:
  chain.link/environment: staging
  chain.link/team: ccip
volumes:
  - name: indexer-toml-config
    configMap:
      name: chainlink-ccv-indexer
  - name: indexer-secrets-toml
    secret:
      secretName: chainlink-ccv-indexer
      items:
        - key: secrets.toml
          path: secrets.toml
volumeMounts:
  - name: indexer-toml-config
    mountPath: /config/indexer.toml
    subPath: indexer.toml
  - name: indexer-secrets-toml
    mountPath: /config/secrets.toml
    subPath: secrets.toml
serviceMonitor:
  enabled: true
service:
  port: 8100
managedDB:
  enabled: true
  engineVersion: "17.4"
  instanceCount: 1
  instanceClass: db.t4g.medium