verifier_id = "tertiary-verifier-1"
aggregator_address = "tertiary-aggregator:50051"
pyroscope_url = "http://pyroscope:4040"
signer_address = "0x1745eFC64c2E61F2E250b7eF79F34c4EC9af092b"

[Monitoring]
Enabled = true
Type = "beholder"
[Monitoring.Beholder]
InsecureConnection = true
CACertFile = ""
OtelExporterGRPCEndpoint = ""
OtelExporterHTTPEndpoint = "otel-collector:4318"
LogStreamingEnabled = true
MetricReaderInterval = 5
TraceSampleRatio = 1.0
TraceBatchTimeout = 10

[on_ramp_addresses]
  3379446385462418246 = "0x610178dA211FEF7D417bC0e6FeD39F05609AD788"
  12922642891491394802 = "0x610178dA211FEF7D417bC0e6FeD39F05609AD788"
  4793464827907405086 = "0x610178dA211FEF7D417bC0e6FeD39F05609AD788"
[committee_verifier_addresses]
  3379446385462418246 = "0x4ed7c70F96B99c776995fB64377f0d4aB3B0e1C1"
  12922642891491394802 ="0x4ed7c70F96B99c776995fB64377f0d4aB3B0e1C1"
  4793464827907405086 = "0x4ed7c70F96B99c776995fB64377f0d4aB3B0e1C1"
[default_executor_on_ramp_addresses]
  3379446385462418246 = "0x322813Fd9A801c5507c9de605d63CEA4f2CE6c44"
  12922642891491394802 = "0x322813Fd9A801c5507c9de605d63CEA4f2CE6c44"
  4793464827907405086 = "0x322813Fd9A801c5507c9de605d63CEA4f2CE6c44"
[rmn_remote_addresses]
  3379446385462418246 = "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"
  12922642891491394802 = "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"
  4793464827907405086 = "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"

[blockchain_infos]
  [blockchain_infos.3379446385462418246]
    ChainID = "1337"
    Type = "anvil"
    Family = "evm"
    UniqueChainName = "blockchain-src"
    [[blockchain_infos.3379446385462418246.Nodes]]
      ExternalHTTPUrl = "http://host.docker.internal:8545"
      InternalHTTPUrl = "http://blockchain-src:8545"
      ExternalWSUrl = "ws://host.docker.internal:8545"
      InternalWSUrl = "ws://blockchain-src:8545"
  [blockchain_infos.12922642891491394802]
    ChainID = "2337"
    Type = "anvil"
    Family = "evm"
    UniqueChainName = "blockchain-dst"
    OfframpRouter = ""

    [[blockchain_infos.12922642891491394802.Nodes]]
      ExternalHTTPUrl = "http://host.docker.internal:8555"
      InternalHTTPUrl = "http://blockchain-dst:8555"
      ExternalWSUrl = "ws://host.docker.internal:8555"
      InternalWSUrl = "ws://blockchain-dst:8555"
  [blockchain_infos.4793464827907405086]
    ChainID = "3337"
    Type = "anvil"
    Family = "evm"
    UniqueChainName = "blockchain-3rd"
    OfframpRouter = ""

    [[blockchain_infos.4793464827907405086.Nodes]]
      ExternalHTTPUrl = "http://host.docker.internal:8565"
      InternalHTTPUrl = "http://blockchain-3rd:8565"
      ExternalWSUrl = "ws://host.docker.internal:8565"
      InternalWSUrl = "ws://blockchain-3rd:8565"
