common:
  image:
    # Use the repo below for non-public builds on any git sha (triggered via Docker Build workflow on the /chainlink repo):
    # repository: 795953128386.dkr.ecr.us-west-2.amazonaws.com/ccip
    # Use the repo below for official releases:
    # repository: public.ecr.aws/chainlink/ccip
    # NOTE: This can be bumped via the image-bump-cd.yaml workflow from this repo for automated deploys. (build)
    repository: 795953128386.dkr.ecr.us-west-2.amazonaws.com/ccip
    tag: manual-520b277
    pullPolicy: IfNotPresent
