common:
  chainlink:
    v2Config:
      01-networks.toml: |
        ## Ethereum Sepolia
        [[EVM]]
          ChainID = "11155111"

          [[EVM.Nodes]]
            HTTPURL = "https://nd-611-802-295.p2pify.com/05541dd996d9d812e580c32477f70b1a"
            Name = "11155111_primary_Chainstack_0"
            SendOnly = false
            WSURL = "wss://ws-nd-611-802-295.p2pify.com/05541dd996d9d812e580c32477f70b1a"

          [[EVM.Nodes]]
            HTTPURL = "https://ethereum-sepolia-1.simplystaking.xyz/DFKJSDFKJNSD/rpc/"
            Name = "11155111_primary_SimplyVC_1"
            SendOnly = false
            WSURL = "wss://ethereum-sepolia-1.simplystaking.xyz/DFKJSDFKJNSD/ws/"

          [[EVM.Nodes]]
            HTTPURL = "https://eth-sepolia-cll.public.linkpool.io/1/cECCLCwZD49G96QyAd2w7ZfrzJr6r9wa"
            Name = "11155111_primary_LinkPool_2"
            SendOnly = false
            WSURL = "wss://eth-sepolia-cll.public.linkpool.io/0/ws/cECCLCwZD49G96QyAd2w7ZfrzJr6r9wa"

        ## Avalanche Fuji
        [[EVM]]
          ChainID = "43113"

          [[EVM.Nodes]]
              HTTPURL = "http://proxy-ingress-nginx-controller.rpc-proxy-2:443/avalanche/fuji"
              Name = "43113_primary_rpcProxy_0"
              SendOnly = false
              WSURL = "ws://proxy-ingress-nginx-controller.rpc-proxy-2:443/avalanche/fuji"

        ## Base Sepolia
        [[EVM]]
          ChainID = "84532"

          [[EVM.Nodes]]
              HTTPURL = "http://proxy-ingress-nginx-controller.rpc-proxy-2:443/base/sepolia"
              Name = "84532_primary_rpcProxy_0"
              SendOnly = false
              WSURL = "ws://proxy-ingress-nginx-controller.rpc-proxy-2:443/base/sepolia"

        ## Arbitrum Sepolia
        [[EVM]]
          ChainID = "421614"

          [[EVM.Nodes]]
              HTTPURL = "http://proxy-ingress-nginx-controller.rpc-proxy-2:443/arbitrum/sepolia"
              Name = "421614_primary_rpcProxy_0"
              SendOnly = false
              WSURL = "ws://proxy-ingress-nginx-controller.rpc-proxy-2:443/arbitrum/sepolia"

        ## Polygon Amoy
        [[EVM]]
          ChainID = "80002"

          [[EVM.Nodes]]
              HTTPURL = "http://proxy-ingress-nginx-controller.rpc-proxy-2:443/polygon/amoy/matrixedlink1"
              Name = "80002_primary_rpcProxy_matrixedlink1_0"
              Order = 99
              SendOnly = false
              WSURL = "ws://proxy-ingress-nginx-controller.rpc-proxy-2:443/polygon/amoy/matrixedlink1"

          [[EVM.Nodes]]
              HTTPURL = "http://proxy-ingress-nginx-controller.rpc-proxy-2:443/polygon/amoy/linkpool1"
              Name = "80002_primary_rpcProxy_linkpool1_0"
              Order = 99
              SendOnly = false
              WSURL = "ws://proxy-ingress-nginx-controller.rpc-proxy-2:443/polygon/amoy/linkpool1"

          [[EVM.Nodes]]
              HTTPURL = "http://proxy-ingress-nginx-controller.rpc-proxy-2:443/polygon/amoy/chainstack1"
              Name = "80002_primary_rpcProxy_chainstack1_0"
              Order = 99
              SendOnly = false
              WSURL = "ws://proxy-ingress-nginx-controller.rpc-proxy-2:443/polygon/amoy/chainstack1"
