common:
  chainlink:
    v2Config:
      ocr-config.toml: &ocr-config |
        [OCR2]
        Enabled = false

      telemetry-config.toml: &telemetry-config |
        [TelemetryIngress]
        UniConn = false
        SendInterval = '250ms'
        BufferSize = 200
        MaxBatchSize = 100

        # # IMPORTANT: Please always use Atlas OTI production for all telemetry endpoints.
        # # Nodes' public keys have to be added to RDD repository to be able to send telemetry data before adding telemetry endpoint.
        # # OTI Connection info https://docs.google.com/spreadsheets/d/1gFFYCTyv81l8BERduM51wceJc5q0wj6MaM5HrRhoh7s/edit?gid=1210952379#gid=1210952379
        # Entries are sorted alphabetically by chain name

        [[TelemetryIngress.Endpoints]]
        # Arbitrum Sepolia
        Network = 'evm'
        ChainID = '421614'
        ServerPubKey = 'd45acffe6bd386d23aebeb3c9ebc2ec30ee806e183d86af2f038420c61a6324e'
        URL = 'ethereum-testnet-sepolia-arbitrum-1.prod.oti.chain.link:8080'

        [[TelemetryIngress.Endpoints]]
        # Base Sepolia
        Network = 'evm'
        ChainID = '84532'
        ServerPubKey = 'c6a9e8cdf8e47cf9d2e5469459fb6d83c72edaac97200646c000e7726e43fed4'
        URL = 'ethereum-testnet-sepolia-base-1.prod.oti.chain.link:8080'

        [[TelemetryIngress.Endpoints]]
        # Ethereum Sepolia
        Network = 'evm'
        ChainID = '11155111'
        ServerPubKey = 'fb894fa9d688bf1378dbfa17e8d2c5d817f1380771e8475dd1676cb6ca64ef4c'
        URL = 'ethereum-testnet-sepolia.prod.oti.chain.link:8080'

        [[TelemetryIngress.Endpoints]]
        # Avalanche Fuji
        Network = 'evm'
        ChainID = '43113'
        ServerPubKey = 'f78d6f3227302fb2a527a4e0a031f10b0595bd831d34fad72fb0fb5b5c9d9ff3'
        URL = 'avalanche-testnet-fuji.prod.oti.chain.link:8080'

        [[TelemetryIngress.Endpoints]]
        # Polygon Amoy
        Network = 'evm'
        ChainID = '80002'
        ServerPubKey = '046f403dff346e20fa75db1cfa4ae5a625bb21ae22d648281ed21bf25fa60c6e'
        URL = 'polygon-testnet-amoy.prod.oti.chain.link:8080'

      evm-config.toml: &evm-config |
        [[EVM]]
        # Avalanche Fuji
        ChainID = '43113'

        [EVM.HeadTracker]
        FinalityTagBypass = false

        [EVM.Transactions]
        ForwardersEnabled = false

        [EVM.GasEstimator]
        LimitDefault = 5000000

        [EVM.GasEstimator.BlockHistory]
        # Default is 24, which leads to bumpy gas prices. In CCIP
        # we want to smooth out the gas prices, so we increase the sample size.
        BlockHistorySize = 200

        [EVM.NodePool]
        PollFailureThreshold = 2
        PollInterval = '3s'

        [[EVM]]
        # Polygon Amoy
        ChainID = '80002'
        FinalityTagEnabled = true
        LinkContractAddress = '0x0Fd9e8d3aF1aaee056EB9e802c3A762a667b1904'
        LogPollInterval = '1s'
        MinIncomingConfirmations = 5
        NoNewHeadsThreshold = '30s'
        RPCBlockQueryDelay = 10
        RPCDefaultBatchSize = 100

        [EVM.Transactions]
        ResendAfterThreshold = '1m'
        MaxQueued = 5000

        [EVM.BalanceMonitor]
        Enabled = true

        [EVM.GasEstimator]
        EIP1559DynamicFees = true
        PriceDefault = '25 gwei'
        PriceMin = '25 gwei'
        BumpMin = '20 gwei'
        BumpThreshold = 5
        PriceMax = '10000 gwei'
        LimitDefault = 8000000
        FeeCapDefault = '10000 gwei'

        [EVM.GasEstimator.BlockHistory]
        # Default is 24, which leads to bumpy gas prices. In CCIP
        # we want to smooth out the gas prices, so we increase the sample size.
        BlockHistorySize = 200

        [EVM.HeadTracker]
        HistoryDepth = 2000
        SamplingInterval = '1s'
        FinalityTagBypass = false

        [EVM.NodePool]
        PollFailureThreshold = 2
        PollInterval = '3s'
        SyncThreshold = 10

        [[EVM]]
        # Base Sepolia
        ChainID = '84532'
        BackupLogPollerBlockDelay = 10

        [EVM.HeadTracker]
        FinalityTagBypass = false

        [EVM.GasEstimator]
        BumpThreshold = 60
        BumpPercent = 20
        BumpMin = '100 wei'
        PriceMax = '120 gwei'
        LimitDefault = 8000000
        FeeCapDefault = '120 gwei'

        [EVM.GasEstimator.BlockHistory]
        # Default is 24, which leads to bumpy gas prices. In CCIP
        # we want to smooth out the gas prices, so we increase the sample size.
        BlockHistorySize = 200
        # The formula for FeeCap is (current block base fee * (1.125 ^ EIP1559FeeCapBufferBlocks) + tipcap)
        # where tipcap is managed by the block history estimators. In the context of CCIP,
        # the gas price is relayed to other changes for quotes so we want accurate/avg not pessimistic values.
        # So we set this to zero so FeeCap = baseFee + tipcap.
        EIP1559FeeCapBufferBlocks = 0

        [EVM.NodePool]
        PollFailureThreshold = 2
        PollInterval = '3s'

        [[EVM]]
        # Ethereum Sepolia
        ChainID = '11155111'

        [EVM.HeadTracker]
        FinalityTagBypass = false

        [EVM.Transactions]
        ForwardersEnabled = false

        [EVM.GasEstimator]
        LimitDefault = 5000000

        [EVM.GasEstimator.BlockHistory]
        # Default is 4!?, which leads to bumpy gas prices. In CCIP
        # we want to smooth out the gas prices, so we increase the sample size.
        BlockHistorySize = 200
        # The formula for FeeCap is (current block base fee * (1.125 ^ EIP1559FeeCapBufferBlocks) + tipcap)
        # where tipcap is managed by the block history estimators. In the context of CCIP,
        # the gas price is relayed to other changes for quotes so we want accurate/avg not pessimistic values.
        # So we set this to zero so FeeCap = baseFee + tipcap.
        EIP1559FeeCapBufferBlocks = 0

        [EVM.NodePool]
        PollFailureThreshold = 2
        PollInterval = '3s'

        [[EVM]]
        # Arbitrum Sepolia
        ChainID = '421614'

        [EVM.HeadTracker]
        FinalityTagBypass = false

        [EVM.Transactions]
        ForwardersEnabled = false

        [EVM.GasEstimator]
        LimitDefault = 5000000

        [EVM.NodePool]
        PollFailureThreshold = 2
        PollInterval = '3s'
