apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.name }}-httproute
spec:
  parentRefs:
    - name: 
      namespace: chainlink-ccv
  hostnames:
    {{- if .Values.ingress.external }}
    - "{{ .Values.name }}.chain.link"
    {{- else }}
    - "{{ .Values.name }}.ccip.{{ .Values.environment }}.internal.griddle.sh"
    {{- end }}
  rules:
    - backendRefs:
        - name: {{ .Values.name }}
          port: {{ .Values.service.port }}