name: golangci-lint

on:
  merge_group:
  pull_request:
  push:
    branches:
      - main

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Read Go version
        id: tool_versions
        shell: bash
        run: |
          echo "go_version=$(grep -E '^VERSION_GO=' tool-versions.env | cut -d= -f2)" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@v6 # v6
        with:
          cache: true
          go-version: ${{ steps.tool_versions.outputs.go_version }}

      - name: Load tool versions
        id: tool-versions
        shell: bash
        run: |
          set -euo pipefail
          source "${GITHUB_WORKSPACE}/tool-versions.env" 

          # Make it a step output
          echo "golangci_lint_version=$VERSION_GOLANGCI_LINT" >> "$GITHUB_OUTPUT"

      - name: Check golangci-lint for root
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 #v8
        with:
          version: "v${{ steps.tool-versions.outputs.golangci_lint_version }}"
          working-directory: ./
          args: --config .golangci.yaml ./...

      - name: Check golangci-lint for build/devenv
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 #v8
        with:
          version: "v${{ steps.tool-versions.outputs.golangci_lint_version }}"
          working-directory: build/devenv/
          args: --config ../../.golangci.yaml ./...

      - name: Check golangci-lint for build/devenv/fakes
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 #v8
        with:
          version: "v${{ steps.tool-versions.outputs.golangci_lint_version }}"
          working-directory: build/devenv/fakes/
          args: --config ../../../.golangci.yaml ./...
